# docker-compose.yml

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000
